var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/city/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lfve4h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_12rthj~.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.zuwp0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_layout_jsx_0q7fn~j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_city_[slug]_page_actions_0.25.zu.js")
R.m(47622)
module.exports=R.m(47622).exports
